import React from 'react';
import { renderMarkdown } from '../../utils/markdownRenderer';
import { Experiment } from '../../config';
import { useToast } from '../../toast';
import { extractJson, tryRepairJson } from '../../services';
import { downloadScientificPaperPdf, downloadScientificPaperDoc, downloadCompleteProjectZip } from '../../utils/scientificPaperExporter';
import { downloadPresentationDeck } from '../../utils/presentationExporter';

interface ExportBundleButtonProps {
    experiment: Experiment;
    publicationText: string;
    contentElementRef?: React.RefObject<HTMLDivElement | null>;
    className?: string;
}

export const ExportBundleButton: React.FC<ExportBundleButtonProps> = ({
    experiment,
    publicationText,
    contentElementRef,
    className = ""
}) => {
    const { addToast } = useToast();

    // Determine the nature of the data source for the disclaimer
    const step6Raw = experiment?.stepData?.[6]?.summary || experiment?.stepData?.[6]?.output || '';
    let isManualData = false;
    try {
        const step6Output = typeof step6Raw === 'string' ? step6Raw : JSON.stringify(step6Raw || '');
        isManualData = step6Output.toLowerCase().includes('manually entered');
    } catch (e) {
        console.error("Error checking manual data", e);
    }

    // Parse the JSON output from the agent
    let publicationData: any = { 
        full_paper: typeof publicationText === 'string' ? publicationText : (publicationText ? JSON.stringify(publicationText) : ''), 
        abstract: "", 
        layman_abstract: "", 
        slides: [] 
    };
    try {
        if (typeof publicationText === 'string' && (publicationText.trim().startsWith('{') || publicationText.includes('```json') || publicationText.includes('full_paper'))) {
            const rawExtracted = extractJson(publicationText);
            try {
                publicationData = JSON.parse(rawExtracted);
            } catch {
                const repaired = tryRepairJson(rawExtracted) || tryRepairJson(publicationText);
                if (repaired) {
                    publicationData = JSON.parse(repaired);
                }
            }
        } else if (typeof (publicationText as any) === 'object' && publicationText !== null) {
            publicationData = { ...publicationData, ...(publicationText as any) };
        }
    } catch (e) {
        console.error("Failed to parse publication JSON", e);
    }

    // Construct the Disclaimer Blocks
    const disclaimerHTML = `
        <div style="background-color: #fff3cd; color: #856404; padding: 20px; border: 1px solid #ffeeba; border-radius: 8px; margin-bottom: 30px; font-family: sans-serif; line-height: 1.5;">
            <div style="font-weight: bold; margin-bottom: 8px; text-transform: uppercase; font-size: 0.9em;">
                ⚠️ AI Generation Disclaimer
            </div>
            <div style="font-size: 0.95em;">
                This research paper was generated by an Artificial Intelligence system. Consequently, it may contain errors, hallucinations, or inaccuracies.
                ${!isManualData ? '<br/><br/><strong>NOTE:</strong> No physical experiments were performed. The results presented here are derived from AI-generated data, code-based simulations, or synthetic datasets. This document is intended strictly for theoretical investigation and ideation.' : ''}
            </div>
        </div>
        <hr style="margin-bottom: 30px; border-top: 1px solid #444;" />
    `;

    const disclaimerText = `⚠️ AI GENERATION DISCLAIMER: This research paper was generated by an Artificial Intelligence system. Consequently, it may contain errors, hallucinations, or inaccuracies.\n${!isManualData ? 'NOTE: No physical experiments were performed. The results presented here are derived from AI-generated data, code-based simulations, or synthetic datasets. This document is intended strictly for theoretical investigation and ideation.\n' : ''}\n---\n\n`;

    const getProcessedManuscriptHtml = () => {
        const rawText = publicationData.full_paper || publicationText || '';
        const textToRender = typeof rawText === 'string' ? rawText : JSON.stringify(rawText);
        let processedText = textToRender;
        const chartPlaceholders = textToRender.match(/\[CHART_(\d+):([\s\S]*?)\]/g) || [];
        
        if (chartPlaceholders.length > 0) {
            const analysisJson = experiment?.stepData?.[7]?.output || '{}';
            let analysisData: any = {};
            try {
                const rawAnalysis = extractJson(analysisJson);
                try {
                    analysisData = JSON.parse(rawAnalysis);
                } catch {
                    const repaired = tryRepairJson(rawAnalysis) || tryRepairJson(analysisJson);
                    if (repaired) analysisData = JSON.parse(repaired);
                }
            } catch(e) {
                console.error("Failed to parse analysis JSON for charts", e);
            }
            const charts = analysisData?.charts || []; 
            
            for (const placeholder of chartPlaceholders) {
                const match = placeholder.match(/\[CHART_(\d+):([\s\S]*?)\]/);
                if (!match) continue;
                
                const chartIndex = parseInt(match[1], 10) - 1;
                const caption = match[2];
                
                if (charts[chartIndex] && charts[chartIndex].imageData) {
                    const dataUrl = `data:image/png;base64,${charts[chartIndex].imageData}`;
                    const imgTag = `<figure style="text-align: center;"><img src="${dataUrl}" alt="${caption}" style="max-width: 80%; height: auto; display: block; margin: 1rem auto; border: 1px solid #444;" /><figcaption style="font-size: 0.9em; color: #aaa; margin-top: 0.5em;">${caption}</figcaption></figure>`;
                    processedText = processedText.replace(placeholder, imgTag);
                } else {
                     processedText = processedText.replace(placeholder, `<p class="text-warning small border border-warning p-2 rounded">[Chart placeholder found but data unavailable for Index ${chartIndex + 1}]</p>`);
                }
            }
        }
        
        const renderedBody = renderMarkdown(processedText);
        return disclaimerHTML + renderedBody;
    };

    const handleDownload = async (format: 'md' | 'doc' | 'pdf' | 'txt' | 'pptx' | 'zip') => {
        const { title, id } = experiment;
        
        if (format === 'zip') {
            addToast("Generating Complete Project Archive ZIP (all 10 stages, paper, code & visualizations)...", "info");
            try {
                await downloadCompleteProjectZip(experiment);
                addToast("Project Archive ZIP downloaded successfully.", "success");
            } catch (err) {
                console.error("Failed to generate ZIP export bundle", err);
                addToast("Failed to generate Export Bundle ZIP.", "danger");
            }
            return;
        }

        if (format === 'pptx') {
            addToast("Generating styled academic presentation (13 widescreen slides)...", "info");
            try {
                await downloadPresentationDeck(experiment, publicationText);
                addToast("PowerPoint presentation (.pptx) downloaded successfully.", "success");
            } catch (err: any) {
                console.error("Failed to download PowerPoint presentation", err);
                addToast(`Failed to generate PowerPoint presentation: ${err?.message || 'Error'}`, "danger");
            }
            return;
        }

        if (format === 'pdf') {
            addToast("Formatting scientific paper into downloadable PDF with citations & appendix...", "info");
            try {
                await downloadScientificPaperPdf(experiment, publicationText);
                addToast("Scientific Paper PDF downloaded successfully.", "success");
            } catch (err) {
                console.error("Failed to generate PDF", err);
                addToast("Failed to generate PDF.", "danger");
            }
            return;
        }
        
        if (format === 'doc') {
            try {
                await downloadScientificPaperDoc(experiment, publicationText);
                addToast("Scientific Paper Word document (.doc) downloaded.", "success");
            } catch (docErr) {
                console.error("Failed to generate Word document:", docErr);
                addToast("Failed to generate Word document.", "danger");
            }
            return;
        }

        const rawContent = format === 'md' ? (publicationData.full_paper || publicationText) : (contentElementRef?.current?.innerText || publicationText);
        const contentWithDisclaimer = disclaimerText + rawContent;
        let blob = new Blob([contentWithDisclaimer], { type: 'text/plain' });
        let filename = `${title.replace(/ /g, '_')}_${id}.${format}`;
        
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = filename;
        link.click();
        URL.revokeObjectURL(url);
        addToast("File exported successfully.", "success");
    };

    return (
        <div className={`btn-group ${className}`}>
            <button 
                type="button" 
                className="btn btn-sm btn-secondary rounded-start-pill px-3" 
                onClick={() => handleDownload('zip')}
                data-tooltip="Downloads ZIP bundle containing Word manuscript, PowerPoint slides, and references"
            >
                <i className="bi bi-file-earmark-zip me-1"></i> Export Bundle (.zip)
            </button>
            <button 
                type="button" 
                className="btn btn-sm btn-secondary dropdown-toggle dropdown-toggle-split rounded-end-pill px-2" 
                data-bs-toggle="dropdown" 
                aria-expanded="false"
                data-tooltip="Opens formats menu (Word, PowerPoint, PDF, Markdown, Text)"
            >
                <span className="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul className="dropdown-menu dropdown-menu-end bg-dark border border-secondary border-opacity-25 shadow">
                <li>
                    <a className="dropdown-item text-light fw-bold" href="#" onClick={(e) => { e.preventDefault(); handleDownload('zip'); }}>
                        <i className="bi bi-file-earmark-zip me-1 text-warning"></i> ZIP Export Bundle (.zip)
                    </a>
                </li>
                <li><hr className="dropdown-divider border-secondary border-opacity-25" /></li>
                <li><a className="dropdown-item text-danger fw-bold d-flex align-items-center" href="#" onClick={(e) => { e.preventDefault(); handleDownload('pdf'); }}><i className="bi bi-file-earmark-pdf-fill me-2 text-danger"></i>PDF Publication (.pdf)</a></li>
                <li><a className="dropdown-item text-light" href="#" onClick={(e) => { e.preventDefault(); handleDownload('md'); }}><i className="bi bi-file-earmark-text me-2"></i>Markdown (.md)</a></li>
                <li><a className="dropdown-item text-light" href="#" onClick={(e) => { e.preventDefault(); handleDownload('txt'); }}><i className="bi bi-file-earmark me-2"></i>Plain Text (.txt)</a></li>
                <li><a className="dropdown-item text-light" href="#" onClick={(e) => { e.preventDefault(); handleDownload('doc'); }}><i className="bi bi-file-earmark-word me-2"></i>Word Document (.docx)</a></li>
                <li><a className="dropdown-item text-light" href="#" onClick={(e) => { e.preventDefault(); handleDownload('pptx'); }}><i className="bi bi-file-earmark-slides me-2"></i>PowerPoint (.pptx)</a></li>
            </ul>
        </div>
    );
};
